name: Deploy to Vercel

on:
  push:
    branches: [configure-cd]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Inject weatherApiKey
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: true," >> src/environments/environment.ts
          echo "  weatherApiKey: '${{ secrets.WEATHER_API_KEY }}'" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Build Angular App
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
